

window.products = [
    // --- Mercado Livre (Agora importados do seu JSON) ---
    {
        "id": 1,
        "name": "Creatina Monohidratada 250g Growth Supplements - Sem sabor em Pó",
        "category": "suplementos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta imperdível do Mercado Livre.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_662415-MLA97812910758_112025-F.webp",
        "link": "https://mercadolivre.com/sec/2h7z9NU",
        "highlight": true
    },
    {
        "id": 2,
        "name": "Câmera De Segurança Wi-fi 360° Hw Lâmpada E27 Full Hd Visão Noturna Colorida Áudio Sensor Movimento Ip",
        "category": "eletronicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Mais uma grande oferta para descobrir.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_726866-MLA99504979854_112025-F.webp",
        "link": "https://mercadolivre.com/sec/32FEwPa",
        "highlight": false
    },
    {
        "id": 3,
        "name": "Kit 4 Cuecas Boxer Lupo Algodão Confortável Box Original",
        "category": "moda",
        "price": 0.00,
        "oldPrice": null,
        "description": "Qualidade e bom preço.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_812578-MLB82638744739_022025-F-kit-4-cuecas-boxer-lupo-algodo-confortavel-box-original.webp",
        "link": "https://mercadolivre.com/sec/2UTY8QQ",
        "highlight": false
    },
    {
        "id": 4,
        "name": "800ml Garrafa Térmica Água Squeeze Inox Academia Quente E Frio",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Confira os detalhes no site.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_963485-MLB94579785063_102025-F-800mlgarrafa-termica-agua-squeeze-inox-academiaquente-e-frio.webp",
        "link": "https://mercadolivre.com/sec/2m2XDGF",
        "highlight": true
    },
    {
        "id": 5,
        "name": "Fechadura Digital de Sobrepor Touch Screen FR 101 Preta Intelbras",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Excelente oportunidade.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_678314-MLA88637512318_072025-F.webp",
        "link": "https://mercadolivre.com/sec/1qTe2C2",
        "highlight": false
    },
    {
        "id": 6,
        "name": "Aspirador De Pó Vertical 3 Em 1 Silent Speed Max 1350w Wap",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Verifique o preço atualizado no link.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_788820-MLU74192085653_012024-F.webp",
        "link": "https://mercadolivre.com/sec/23A54KT",
        "highlight": false
    },
    {
        "id": 7,
        "name": "Strike Removedor Piche Asfalto Cola Adesivo Vonixx 500ml",
        "category": "automotivo",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta especial.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_906196-MLA99448129206_112025-F.webp",
        "link": "https://mercadolivre.com/sec/16djxWQ",
        "highlight": false
    },
    {
        "id": 8,
        "name": "Liquidificador Philco 1200W 3L 12 Velocidades Preto PH900",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Aproveite esta oferta.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_766837-MLA98259429221_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1fFD8rW",
        "highlight": false
    },
    {
        "id": 9,
        "name": "Principia Sérum 10% Niacinamida + 1% Zinco Pca NC-10 30 mL",
        "category": "beleza",
        "price": 0.00,
        "oldPrice": null,
        "description": "Promoção imperdível.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_743512-MLA96768387527_102025-F.webp",
        "link": "https://mercadolivre.com/sec/2iWXAQ5",
        "highlight": false
    },
    {
        "id": 10,
        "name": "Parafusadeira Furadeira C/ 2 Baterias Maleta Kit Completo Led",
        "category": "ferramentas",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_828436-MLA100007265481_122025-F.webp",
        "link": "https://mercadolivre.com/sec/2PhKTK8",
        "highlight": false
    },
    {
        "id": 11,
        "name": "NIVEA SUN Protetor Solar Facial Toque Seco Antissinais FPS70 40ml, Alta Proteção UVA/UVB, Controla a Oleosidade, Previne Envelhecimento, Textura Leve",
        "category": "Beleza",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_990747-MLA105989506287_012026-F.webp",
        "link": "https://mercadolivre.com/sec/2FxkGwT",
        "highlight": false
    },
    {
        "id": 12,
        "name": "Plus do Brasil Cabo Usb Turbo Tipo C Compativel Com Samsung Galaxy S25 S24 Plus S23 Fe S22 S21 S20 A16 A15 A22 A13 A14 A55 A53 A54 A06 A05s A20 A21 Apple iPhone 17 16 15 Carplay Auto Android",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_724447-MLA106895488253_022026-F.webp",
        "link": "https://mercadolivre.com/sec/2cgkAwS",
        "highlight": false
    },
    {
        "id": 13,
        "name": "Filamento Pla Velvet Preto 1kg",
        "category": "Diversos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_872979-MLA97109618044_112025-F.webp",
        "link": "https://mercadolivre.com/sec/327tQtz",
        "highlight": false
    },
    {
        "id": 14,
        "name": "Bicicleta Rosa Nathor Flower Infantil Aro 12 Menina Cestinha",
        "category": "Lazer",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_642327-MLA99888118883_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1FgymU4",
        "highlight": false
    },
    {
        "id": 15,
        "name": "Afiador E Amolador De Facas E Tesouras 4 Em 1 Profissional ",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_745769-MLA106573280695_022026-F.webp",
        "link": "https://mercadolivre.com/sec/2NamnKQ",
        "highlight": false
    },
    {
        "id": 16,
        "name": "Kit 4 Rodízio Giratório Gel Silicone Rodinha Móveis 50mm - Compra Segura Ekom ",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_701301-MLA105259227459_012026-F.webp",
        "link": "https://mercadolivre.com/sec/1Fm183e",
        "highlight": false
    },
    {
        "id": 17,
        "name": "Espelho Vildrex Roma 70x50cm Design Moderno Lapidado Luxo",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_737366-MLB95371198573_102025-F-espelho-vildrex-roma-70x50cm-design-moderno-lapidado-luxo.webp",
        "link": "https://mercadolivre.com/sec/1Fm183e",
        "highlight": false
    },
    {
        "id": 18,
        "name": "Smart Tv 32 Philco P32vik Roku Led Dolby Audio Hdr Wi-fi 110/220v",
        "category": "Eletronicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_691057-MLA100479527690_122025-F.webp",
        "link": "https://mercadolivre.com/sec/2BvmJas",
        "highlight": false
    },
    {
        "id": 19,
        "name": "Mixer Power Inox 3 Em 1 600w Elgin Lunar",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_884782-MLA100072923939_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1g4QEg3",
        "highlight": false
    },
    {
        "id": 20,
        "name": "Capa Colchão Impermeável Hospitalar Antialérgico Solteiro",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_926506-MLA96049314300_102025-F.webp",
        "link": "https://mercadolivre.com/sec/2ik2cpz",
        "highlight": false
    },
    {
        "id": 21,
        "name": "Mini Compressor Digital Simake Bomba De Encher Pneus Portátil Para Carro Bicicleta Motocicletas Cor Preto Com Calibrador",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_900674-MLA100087555981_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1snGmJw",
        "highlight": false
    },
    {
        "id": 22,
        "name": "Percarbonato De Sódio 1 Kg Tira Manchas Alvejante Sem Cloro 1 Kg",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_648597-MLB95229878600_102025-F.webp",
        "link": "https://mercadolivre.com/sec/2DAYuoU",
        "highlight": false
    },
    {
        "id": 23,
        "name": "Elgin plafon painel quadrado sobrepor 24w branco frio 6500k estrutura branco-frio",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_765319-MLA100105841965_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1AhoiYW",
        "highlight": false
    },
    {
        "id": 24,
        "name": "Robô aspirador Robot W90 varre aspira e passa pano 30w Wap cor preto",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_748103-MLA99906601653_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1L8jaQh",
        "highlight": false
    },
    {
        "id": 25,
        "name": "Aspirador Piscina Manual Netuno Venturi Nv Azul",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_740298-MLA95495291638_102025-F.webp",
        "link": "https://mercadolivre.com/sec/2DeBoZj",
        "highlight": false
    },
    {
        "id": 26,
        "name": "Colchonete 90x40x3 Academia Impermeável Fit Yoga Ginastica Preto",
        "category": "Exercicios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_833684-MLA99608314112_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1cei5te",
        "highlight": false
    },
    {
        "id": 27,
        "name": "Carregador Turbo Duplo 40w Usb Tipo C Para iPhone 8 X Xr 11 12 13 14 Pro Max Dtimp",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_609505-MLA105673814081_012026-F.webp",
        "link": "https://mercadolivre.com/sec/1bmwehB",
        "highlight": false
    },
    {
        "id": 28,
        "name": "Escorredor de Louças Compacto 13 Pratos Porta Talher Preto Metaltru",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_956987-MLA99618172634_122025-F.webp",
        "link": "https://mercadolivre.com/sec/22YG9yp",
        "highlight": false
    }, {
        "id": 29,
        "name": "We Varejo - Raquete Mata Mosca Elétrica Bateria Recarregável Portátil Pega Mosquitos Penilogos Matar Insetos",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_928009-MLA105666481248_012026-F.webp",
        "link": "https://mercadolivre.com/sec/22YG9yp",
        "highlight": false
    },
    {
        "id": 30,
        "name": "Roçadeira Nakasaki 75cc 3.6hp Gasolina 6 Em 1 Nk750pro",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_852970-MLB107008940939_022026-F.webp",
        "link": "https://mercadolivre.com/sec/2iwKyDY",
        "highlight": false
    },
    {
        "id": 31,
        "name": "Tapete Higiênico 50 Unidades (60x55) Descartável Manta Fralda Absorvente Gel Para Cachorro Pet Cão",
        "category": "PET",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_916620-MLA100071703077_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1bmwehB",
        "highlight": false
    },
    {
        "id": 32,
        "name": "Smartwatch Xiaomi Redmi Watch 5 Active Tela Lcd 2.00 Preto",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_949046-MLA99507276886_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1WUrWwi",
        "highlight": false
    },
    {
        "id": 33,
        "name": "Smart Tv Samsung U8100f Crystal Uhd 4k 2025 43 Preto",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_648933-MLA99498284868_112025-F.webp",
        "link": "https://mercadolivre.com/sec/2jZHSG1",
        "highlight": false
    },
    {
        "id": 34,
        "name": "Varal De Chão Grande De Roupas 3 Andares Dobrável Cor Azul Kontuz 170 cm",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_968619-MLA99977372933_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1bmwehB",
        "highlight": false
    },
    {
        "id": 35,
        "name": "Mochila Masculina Impermeável Reforçada Aço Escola Notebook Preto Liso",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_839933-MLB98920410204_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1SRddV2",
        "highlight": false
    },
    {
        "id": 36,
        "name": "Grill Sanduicheira Cadence SAN400 Elétrica Chapa Misteira Tostex Tostequeira Hambúrguer Click",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_934834-MLA99525616894_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1YrU5Sw",
        "highlight": false
    },
    {
        "id": 37,
        "name": "Desodorante Pedra Sal Hi Cool Cristal Vegano, Crystal Deo Stick Sem cheiro - Natural Sem Fragrância 60g Sem Alumínio Antiodor",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_899521-MLA99924804553_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1Rgai3B",
        "highlight": false
    },
    {
        "id": 38,
        "name": "Tomada Inteligente Smart Wifi Controle Automação Ekaza 16a",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_953374-MLA96319906125_102025-F.webp",
        "link": "https://mercadolivre.com/sec/1sNuRMj",
        "highlight": false
    },
    {
        "id": 39,
        "name": "Cabine Seca Esmalte Sun5 Maquina Unha Gel Bivolt Alongamento Cor Branca",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_819531-MLU78007495484_082024-F.webp",
        "link": "https://mercadolivre.com/sec/2J8aYqM",
        "highlight": false
    },
    {
        "id": 40,
        "name": "Fone De Ouvido Para Capacete Bluetooth Headset Rgb Sem Fio Kateluo",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_772892-MLA99449981056_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1GekNPo",
        "highlight": false
    },
    {
        "id": 41,
        "name": "Smart Tv 32 Philco Ptv32k34rkgb Roku Tv Led Dolby Audio",
        "category": "Eletronicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_681053-MLA99382614472_112025-F.webp",
        "link": "https://mercadolivre.com/sec/2jj3GhK",
        "highlight": false
    },
    {
        "id": 42,
        "name": "Luz Para Gravar Videos + Suporte Celular+tripe Mesa Envio24h Estrutura Preto Luz Branco-quente/ branco-frio/neutro",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_647793-MLA99599827388_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1paSiXa",
        "highlight": false
    },
    {
        "id": 43,
        "name": "Régua Extensão Elétrica 6 Tomadas Filtro Linha 10a Cabo 1 Metro",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_685971-MLA95634606208_102025-F.webp",
        "link": "https://mercadolivre.com/sec/1TQ78Az",
        "highlight": false
    },
    {
        "id": 44,
        "name": "Kit 2 Und Percarbonato De Sódio Tira Manchas Roupas 2 Kilos",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_836069-MLB91371055917_082025-F.webp",
        "link": "https://mercadolivre.com/sec/1CbxYSE",
        "highlight": false
    },
    {
        "id": 45,
        "name": "Repelente Eletrico Líquido Raid 45 Noites 3 Refis de 32,9ml",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_767964-MLA97523997048_112025-F.webp",
        "link": "https://mercadolivre.com/sec/31R56vH",
        "highlight": false
    },
    {
        "id": 46,
        "name": "Kit2 Tapetes Para Banheiro Tapete Mágico Ultra Para Absorção",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_723164-MLB101848516780_122025-F-kit2-tapetes-para-banheiro-tapete-magico-ultra-para-absorc.webp",
        "link": "https://mercadolivre.com/sec/1d4GLQV",
        "highlight": false
    },
    {
        "id": 47,
        "name": "Assento de Carro Infantil Elevação Booster Fit Up 15 à 36kgs Preto Replay Kids 21423",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_886802-MLA99508601024_112025-F.webp",
        "link": "https://mercadolivre.com/sec/15zGpNb",
        "highlight": false
    },
    {
        "id": 48,
        "name": "Principia Kit Gel de Limpeza GL-01 + Protetor Solar Facial PS-01 FPS 60",
        "category": "Higiene",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_908971-MLA103561914983_012026-F.webp",
        "link": "https://mercadolivre.com/sec/1xLBmyg",
        "highlight": false
    },
    {
        "id": 49,
        "name": "Dermaroller 0.5mm 540 Agulhas Derma Roller System",
        "category": "Diversos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_783278-MLA98930670296_112025-F.webp",
        "link": "https://mercadolivre.com/sec/2t9XNiS",
        "highlight": false
    },
    {
        "id": 50,
        "name": "Grade Portão Preto Proteção Pets 68 A 73 / 78 A 83 Cm Cachorro aramado 69cm",
        "category": "PET",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_959247-MLA102611680880_122025-F.webp",
        "link": "https://mercadolivre.com/sec/2P8WJqi",
        "highlight": false
    },
    {
        "id": 51,
        "name": "Chave T 10mm Longa 62cm Para Maquina De Lavar",
        "category": "Ferramentas",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_711839-MLB85121376643_052025-F.webp",
        "link": "https://mercadolivre.com/sec/13NHiSy",
        "highlight": false
    },
    {
        "id": 52,
        "name": "Purificador de Água Gelada Fria e Natural Eletronico Placa Compacto Electrolux PE12B com Filtro Carvão 6 meses ou 3000L Painel Touch Branco",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_761091-MLA99918405251_112025-F.webp",
        "link": "https://mercadolivre.com/sec/2c6MuM9",
        "highlight": false
    },
    {
        "id": 53,
        "name": "Gillette Mach3 Sensitive carga de barbeador 8 unidades",
        "category": "Higiene",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_603981-MLA99425801092_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1NcLjR6",
        "highlight": false
    },
    {
        "id": 54,
        "name": "Conj de Panelas 8 Peças Ceramic Life Smart Plus Vanilla - Brinox",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_803604-MLA95708299394_102025-F.webp",
        "link": "https://mercadolivre.com/sec/13DF7HR",
        "highlight": false
    },
    {
        "id": 55,
        "name": "Câmera Segurança Ip Externa Wifi A28 App Icsee Prova Dagua IP66 Dome Lente Dupla Lentes 2 Em 1 Vigilancia Visão Noturna Infravermelho Casenn",
        "category": "Ferramentas",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_635583-MLA100019457791_122025-F.webp",
        "link": "https://mercadolivre.com/sec/15J2zFg",
        "highlight": false
    },
    {
        "id": 56,
        "name": "Panela De Arroz Fast Rice 5 Premium Mondial 400W - NPE-08-5X",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_980379-MLA100008293867_122025-F.webp",
        "link": "https://mercadolivre.com/sec/2xsStJp",
        "highlight": false
    },
    {
        "id": 57,
        "name": "Console Playstation 5 Slim Edição Digital 825 Gb",
        "category": "Eletrônicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_677584-MLA99572203884_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1kubhnr",
        "highlight": false
    },
    {
        "id": 58,
        "name": "Volante gamer Logitech G29 G29 DRIVING FORCE cor preto",
        "category": "Eletrônicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_730363-MLA99890032125_112025-F.webp",
        "link": "https://mercadolivre.com/sec/2o3bRpj",
        "highlight": false
    },
    {
        "id": 59,
        "name": "Caixa De Som Partybox Encore 2 Com Microfone Jbl Preto",
        "category": "Eletrônicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_734366-MLA99936636035_112025-F.webp",
        "link": "https://mercadolivre.com/sec/1oaANzV",
        "highlight": false
    },
    {
        "id": 60,
        "name": "Kit 6 Cuecas Lupo Boxer Box Sem Costura Basic Microfibra",
        "category": "Moda",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_724774-MLB100762267821_122025-F-kit-6-cuecas-lupo-boxer-box-sem-costura-basic-microfibra.webp",
        "link": "https://mercadolivre.com/sec/2zpKygM",
        "highlight": false
    },
    {
        "id": 61,
        "name": "Parafusadeira Furadeira De Impacto The Black Tools Profissional TB-21PX 2 Baterias Com Maleta 60Hz Amarelo",
        "category": "Ferramentas",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_865332-MLA96868279679_102025-F.webp",
        "link": "https://mercadolivre.com/sec/1vx2aCG",
        "highlight": false
    },
    {
        "id": 62,
        "name": "Limpa Maquina De Lavar Roupas Pastilha Limpeza 12 Unidades",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_994208-MLB101086743845_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1mqk2WY",
        "highlight": false
    }, {
        "id": 63,
        "name": "Kit 6 Pares Meias Puma Cano Médio Alto Atoalhada Original",
        "category": "Moda",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_617361-MLB54128842596_032023-F-kit-6-pares-meias-puma-cano-medio-alto-atoalhada-original.webp",
        "link": "https://mercadolivre.com/sec/1NwBHJA",
        "highlight": false
    },
    {
        "id": 64,
        "name": "Notebook Acer Aspire Go 15 AG15-51P-39MU â€“ Intel Core i3-1305U 13Âª GeraÃ§Ã£o â€¢ 8GB DDR5 RAM â€¢ 256GB SSD â€¢ Tela 15,3' â€¢ Windows 11 Home",
        "category": "Eletrônicos",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_692920-MLA100061644521_122025-F.webp",
        "link": "https://mercadolivre.com/sec/2LZzRBz",
        "highlight": false
    },
    {
        "id": 65,
        "name": "Capa Impermeável Para Carro Proteção Total Uv Chuva",
        "category": "Acessórios",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_647333-MLB96268103903_102025-F-capa-impermeavel-para-carro-proteco-total-uv-chuva.webp",
        "link": "https://mercadolivre.com/sec/12t8TK2",
        "highlight": false
    },
    {
        "id": 66,
        "name": "Filtro De Café Reutilizável Em Aço Inox Modelo 103 Peneira Permanente Sustentável Coar Café Tradicional Sem Papel Econômico E Durável Ponte Lar Utilidades",
        "category": "Casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Melhor custo-benefício.",
        "image": "https://http2.mlstatic.com/D_NQ_NP_2X_803581-MLA99564243074_122025-F.webp",
        "link": "https://mercadolivre.com/sec/1TSg8F4",
        "highlight": false
    },

    // --- Shopee (Importados) ---
    {
        "id": 101,
        "name": "Kit 10 Pote de Vidro Hermético Retangular 4 Travas Marmita",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Achadinho da Shopee.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-821ep-mgjgq4m9ssgf89.webp",
        "link": "https://s.shopee.com.br/6VIJly5Jkf",
        "highlight": true
    },
    {
        "id": 102,
        "name": "Mochila Escolar Feminina Material Escolar Completo",
        "category": "moda",
        "price": 0.00,
        "oldPrice": null,
        "description": "Produto incrível da Shopee.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mj8r67pdw5c2c2@resize_w900_nl.webp",
        "link": "https://s.shopee.com.br/8AQXlDPX9s",
        "highlight": false
    },
    {
        "id": 103,
        "name": "Kit 10 Esmaltes Impala Marrom Nude Esmalte Capivara",
        "category": "beleza",
        "price": 0.00,
        "oldPrice": null,
        "description": "Desconto especial.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mc9dux5ewycr4e@resize_w900_nl.webp",
        "link": "https://s.shopee.com.br/7pnhMv5Jmp",
        "highlight": false
    },
    {
        "id": 104,
        "name": "Copo Térmico Grande 1200ml Em Aço Inox Com Alça",
        "category": "casa",
        "price": 0.00,
        "oldPrice": null,
        "description": "Verifique a disponibilidade.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7rfgq-m9ex0vr1fnonf6.webp",
        "link": "https://s.shopee.com.br/4VXFOsXiyq",
        "highlight": true
    },
    {
        "id": 105,
        "name": "Espuma Limpa Estofados a seco Magica 300ml Kit",
        "category": "automotivo",
        "price": 0.00,
        "oldPrice": null,
        "description": "Clique em Ver Oferta.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m8xer7tqkxkyde.webp",
        "link": "https://s.shopee.com.br/8AQXlf5M3g",
        "highlight": false
    },
    {
        "id": 106,
        "name": "Cooler Multifuncional Super Térmica 32 Litros",
        "category": "lazer",
        "price": 0.00,
        "oldPrice": null,
        "description": "Aproveite esta promoção.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfe54je0p345ca@resize_w900_nl.webp",
        "link": "https://s.shopee.com.br/8V3OANwrHo",
        "highlight": false
    },
    {
        "id": 107,
        "name": "Kit 10 Pote de Vidro Hermético Retangular 4 Travas Marmita Fit Microondas Mantimentos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-821ep-mgjgq4m9ssgf89.webp",
        "link": "https://s.shopee.com.br/6VIJly5Jkf",
        "highlight": false
    },
    {
        "id": 108,
        "name": "Material Escolar Completo Com Sem Estojo Escolar Feminino Mochila Escolar Feminina Volta As aulas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mj8r67pdw5c2c2.webp",
        "link": "https://s.shopee.com.br/8AQXlDPX9s",
        "highlight": false
    },
    {
        "id": 109,
        "name": "Kit 10 Esmaltes Impala Marrom Nude Esmalte Capivara Atacado",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcqiikvwpohe7b.webp",
        "link": "https://s.shopee.com.br/7pnhMv5Jmp",
        "highlight": false
    },
    {
        "id": 110,
        "name": "Copo Térmico Grande 1200ml Em Aço Inox Com Alça E Canudo Metal Cor Vibrante",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/4VXFOsXiyq",
        "highlight": false
    },
    {
        "id": 111,
        "name": "Espuma Limpa Estofados a seco Magica Remove sujeira Tecidos Tapetes Sofás Colchoes Carpetes Tetos 300ml kit",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/8AQXlf5M3g",
        "highlight": false
    },
    {
        "id": 112,
        "name": "Cooler Multifuncional Super Térmica 32 Litros Casa Praia Camping Viagens Multiuso",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfe54je0p345ca.webp",
        "link": "https://s.shopee.com.br/8V3OANwrHo",
        "highlight": false
    },
    {
        "id": 113,
        "name": "Balança Inteligente com Bioimpedância, App Integrado e Capacidade de até 180kg",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7ra18-mbg5xr4kqmq5a0.webp",
        "link": "https://s.shopee.com.br/7VAqya4Bka",
        "highlight": false
    },
    {
        "id": 114,
        "name": "Kit 10 Marmita fitness Potes 800ml Travas Laterais --> BPA FREE organizadores de alimentos vasilhas.",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mckte4fnpkht93.webp",
        "link": "https://s.shopee.com.br/5fjCnFf5aj",
        "highlight": false
    },
    {
        "id": 115,
        "name": "Kit 2 Câmera Segurança Prova D'água Infravermelho Lâmpada Externa 360 Sem Fio Wifi 2.4G G4",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mf7qosc36l8mc3.webp",
        "link": "https://s.shopee.com.br/6pvABR0J5k",
        "highlight": false
    },
    {
        "id": 116,
        "name": "Cortador, Fatiador e Ralador Manual Multifuncional De Legumes e Alimentos (12 funções)",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/70EaNm3OyL",
        "highlight": false
    },
    {
        "id": 117,
        "name": "Material Escolar Stitch e Angel Mochila Lancheira Estojo Original Disney Luxcel",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/14q2wOqJ3",
        "highlight": false
    },
    {
        "id": 118,
        "name": "Jogo de Lençol 400 Fios Micropercal Com Fronha em Ponto Palito",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/8fMoMuQAd5",
        "highlight": false
    },
    {
        "id": 119,
        "name": "Cozedor De Ovos Portátil Elétrico Cozinha A Vapor 110v/220v",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mbxi2wd1amvtfc.webp",
        "link": "https://s.shopee.com.br/8fMoMwgp8r",
        "highlight": false
    },
    {
        "id": 120,
        "name": "Protetor Lençol Ajustável Impermeável Avulso Para Colchão Berço, Solteiro, Casal, Queen e King",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7mjziggp1s2c2.webp",
        "link": "https://s.shopee.com.br/AUoSYLddu4",
        "highlight": false
    },
    {
        "id": 121,
        "name": "Protetor Lençol Ajustável Impermeável Avulso Para Colchão Berço, Solteiro, Casal, Queen e King",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7mjziggp1s2c2.webp",
        "link": "https://s.shopee.com.br/6fbjzLiDyq",
        "highlight": false
    },
    {
        "id": 122,
        "name": "KIT lili 350ml creme e perfume acetinado corpo e mãos hidratante lily lulli cuide se bem",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/9KcVAH2GDb",
        "highlight": false
    },
    {
        "id": 123,
        "name": "Bicicleta elétrica dobrável para adultos NUDA, pedal tripulado, compras ao ar livre, viagem",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mj0pubc1kdty09.webp",
        "link": "https://s.shopee.com.br/2LSkpSAEgN",
        "highlight": false
    },
    {
        "id": 124,
        "name": "Kit Taças De Vidro Diamond Greek Para Vinho E Água 330 ML",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgoeeocm3i10f5.webp",
        "link": "https://s.shopee.com.br/9UvvMei93G",
        "highlight": false
    },
    {
        "id": 125,
        "name": "Kit 3 Unidades Sabonete Líquido Chá Branco 500 ml",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/9pYllJF826",
        "highlight": false
    },
    {
        "id": 126,
        "name": "Kit Completo Karseell Máscara 500 g + condicionador 1L + Shampoo 1L + Óleo karseell P 50ml",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/W16eBwmxM",
        "highlight": false
    },
    {
        "id": 127,
        "name": "Jogo de Lençol Percal 180 Fios 100% Algodão – Todos os Tamanhos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mflnn6x2u6tgc4.webp",
        "link": "https://s.shopee.com.br/3qHYcMDx3m",
        "highlight": false
    },
    {
        "id": 128,
        "name": "kit Coala Home Chá Branco",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/4AuP10KfrW",
        "highlight": false
    },
    {
        "id": 129,
        "name": "Fone de Ouvido Bluetooth Sem Fio Digital Alta Qualidade Intra Auricular M47",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m2dgumrr891y18.webp",
        "link": "https://s.shopee.com.br/4fqfbxQy6X",
        "highlight": false
    },
    {
        "id": 130,
        "name": "Kit com 15 potes herméticos plásticos para cozinha",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcx088rti8fm2c.webp",
        "link": "https://s.shopee.com.br/7VAqzCSVLy",
        "highlight": false
    },
    {
        "id": 131,
        "name": "Escova De Limpeza 9 Em1 Recarregavél Elétrica Giratória Com Cabo Alongador",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mie9qo52n952e9.webp",
        "link": "https://s.shopee.com.br/9fFLZDJNbP",
        "highlight": false
    },
    {
        "id": 132,
        "name": "ROMANTIC CROWN Copo Térmico Portátil 1200ml/600ml com Tampa e Canudo Garrafa Térmica Inoxidável À prova de vazamentos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mi59t0ijd1ja72.webp",
        "link": "https://s.shopee.com.br/1VtdqEnf5F",
        "highlight": false
    },
    {
        "id": 133,
        "name": "Aparelho Medidor De Pressão Arterial De Braço Digital Inteligente-XHL HOME",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcgs7j5l6kn56f.webp",
        "link": "https://s.shopee.com.br/4AuP1Aclqh",
        "highlight": false
    },
    {
        "id": 134,
        "name": "Kit 6 Potes Para Tempero 200ml Vidro Hermético Tampa Bambu Alta Vedação Mantimentos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mf1ge9dcz85j30.webp",
        "link": "https://s.shopee.com.br/6KytbBTiMY",
        "highlight": false
    },
    {
        "id": 135,
        "name": "5/10/20 Peças Pano Absorvente Anti Óleo Para Cozinha /Pano De Microfibra /Toalha De Limpeza De Cozinha/Toalha De Mesa",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lqd6me8400lf26.webp",
        "link": "https://s.shopee.com.br/7AY0akYOcT",
        "highlight": false
    },
    {
        "id": 136,
        "name": "Mini Liquidificador Portátil De Suco De Alimentos Misturador Leite Smoothie 400ML 6 Lâminas Espremedor Elétrico",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-8225t-mhgsig1u016q21.webp",
        "link": "https://s.shopee.com.br/7AY0amkmsV",
        "highlight": false
    },
    {
        "id": 136,
        "name": "Kit Pote de Vidro Hermético Retangular 10 / 5 Unid Travas Marmita Fit Microondas Mantimentos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdn5xvzwinrl9c.webp",
        "link": "https://s.shopee.com.br/6VIJnb4K3d",
        "highlight": false
    },
    {
        "id": 137,
        "name": "Limpa Air Fryer Spray 250ml Super Dom – Remove Gordura Pesada, Limpeza Rápida e Fácil Uso",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdb91lc0nke993.webp",
        "link": "https://s.shopee.com.br/7fUHBm3Gcm",
        "highlight": false
    },
    {
        "id": 138,
        "name": "Espelho Oval Com Led orgânico Lapidado Luxo Quarto Sala Banheiro Grande Em Várias Medidas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-maldtkjlxwqhd8.webp",
        "link": "https://s.shopee.com.br/7AY0at4V3D",
        "highlight": false
    },
    {
        "id": 139,
        "name": "Colar Personalizado Feminino 17mm Foto Gravação 45cm Banho Ouro 18k Acessórios Presente Dia das Mulheres",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mdyouuexi58j3b.webp",
        "link": "https://s.shopee.com.br/7AY0av7xDN",
        "highlight": false
    },
    {
        "id": 140,
        "name": "Conjunto Fitness Aurora",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcwsxy6yyalu20.webp",
        "link": "https://s.shopee.com.br/7fUHBrNJYP",
        "highlight": false
    },
    {
        "id": 141,
        "name": "Saco de Lixo Cheiroso Lavanda 10L Saco de lixo Perfumado Neutraliza Odor Pia Banheiro Perfume Suave",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgo23le6pkw073.webp",
        "link": "https://s.shopee.com.br/8077aUdExY",
        "highlight": false
    },
    {
        "id": 142,
        "name": "Garrafa Térmica Zaya Tuut 1L Canelada Design Sofisticado, Mantém Bebidas Quentes E Frias, Ideal Para Café E Chá",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/7VAqzaND3k",
        "highlight": false
    },
    {
        "id": 143,
        "name": "Tapete Bolinha Antiderrapante Para Banheiro Alta Absorção",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-meeslzzebqbn4d.webp",
        "link": "https://s.shopee.com.br/1BGnRxKRuX",
        "highlight": false
    },
    {
        "id": 144,
        "name": "Kit 3 Calças Feminina Legging Grossa Para Academia Fitness Cós Alto",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mid5u9sjfjlvf3.webp",
        "link": "https://s.shopee.com.br/4VXFQ6l1P6",
        "highlight": false
    },
    {
        "id": 145,
        "name": "Passadeira 110v Ferro a Vapor Vaporizador de Roupas Tira Amasso Portátil 800W",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7ra14-mblim39p40p934.webp",
        "link": "https://s.shopee.com.br/7AY0b15bDM",
        "highlight": false
    },
    {
        "id": 146,
        "name": "40 Peças / 46 Peças Jogo De Chave Catraca Caixa De Ferramentas Completa Reversível Soquetes Maleta",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7rfi6-m96pnweedbdz0a.webp",
        "link": "https://s.shopee.com.br/3qHYctvokp",
        "highlight": false
    },
    {
        "id": 147,
        "name": "Kit Potes Vidro CANELADO ÂMBAR CRISTAL Porta Mantimentos cozinha Tampa Bambu Argola Dourada PMG porta tempero",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9089s5vty4ice.webp",
        "link": "https://s.shopee.com.br/9pYllw8Nct",
        "highlight": false
    },
    {
        "id": 148,
        "name": "Kit 5 Calcinhas Sem costura Tanga corte a Laser PROMOÇÃO Não Marca na Roupa",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7ratx-maaleuuypc3p1c.webp",
        "link": "https://s.shopee.com.br/6AfTPD8Wsy",
        "highlight": false
    },
    {
        "id": 149,
        "name": "Garrafa Térmica 800ml Com Base De Silicone Removível Aço Inoxidável Quente/Frio",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-md1vili5g7i9e7.webp",
        "link": "https://s.shopee.com.br/6pvACS9zGx",
        "highlight": false
    },
    {
        "id": 150,
        "name": "Air Fryer Fritadeira Elétrica Digital Extream 4,3L",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mid7bqa05y4hdd.webp",
        "link": "https://s.shopee.com.br/LhgSWGnY1",
        "highlight": false
    },
    {
        "id": 151,
        "name": "Kit Pneu Pretinho Shampoo V-Floc Cera Tok Final Carnauba Vonixx Oferta de Carnaval",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m3xv9xcl2jp447.webp",
        "link": "https://s.shopee.com.br/2VmB2VdHOX",
        "highlight": false
    },
    {
        "id": 152,
        "name": "Extensão 5 Tomadas 4 USB 2 TypeC Universal Bivolt 110v/220v 2500W Power 2m Filtro De Linha Segurança",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-md0ogsxtyz29c9.webp",
        "link": "https://s.shopee.com.br/1VtdqgKtE1",
        "highlight": false
    },
    {
        "id": 153,
        "name": "Capa Chuva Sapato Premium Protetor Pé Tênis Moto Adulto Impermeável Motoqueiro Calçado",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lwk0nro3aahebd.webp",
        "link": "https://s.shopee.com.br/5fjCoLe1FG",
        "highlight": false
    },
    {
        "id": 154,
        "name": "Conjunto Academia Top Fitness e Legging Cintura Alta Zero Transparência Suplex Strep Original",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfmnz57sjguda6.webp",
        "link": "https://s.shopee.com.br/3fy8QgPMs3",
        "highlight": false
    },
    {
        "id": 155,
        "name": "Kit com 20 unidades de Temperos e Condimentos para sua Cozinha mais vendido temperos e condimentos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m51gkui3kp0ybb.webp",
        "link": "https://s.shopee.com.br/50TW19Jkbx",
        "highlight": false
    },
    {
        "id": 156,
        "name": "40 Peças / 46 Peças Jogo De Chave Catraca Caixa De Ferramentas Completa Reversível Soquetes Maleta",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfrvxdr9i96v11.webp",
        "link": "https://s.shopee.com.br/5VPmc5DBII",
        "highlight": false
    },
    {
        "id": 157,
        "name": "Percarbonato Sódio 3kg Tira Mancha Roupa Calisul 100% Puro",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mg81kz9j05qdcb.webp",
        "link": "https://s.shopee.com.br/9AJ4ypcgM4",
        "highlight": false
    },
    {
        "id": 158,
        "name": "Chaleira Elétrica Inox 1,8L 110V Térmica Café Chá Água Quente Desligamento Automático Ferve Rápido",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m5bmj4ff46f920.webp",
        "link": "https://s.shopee.com.br/4qA5osO2tu",
        "highlight": false
    },
    {
        "id": 159,
        "name": "Kit Completo Karseell Máscara 500 g + condicionador 1L + Shampoo 1L + Óleo karseell P 50ml",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/1LaDeSAhmG",
        "highlight": false
    },
    {
        "id": 160,
        "name": "Escova de Limpeza Elétrica 5 em 1: A Solução Completa para Cozinha, Banheiro e Sapatos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mitl9ye75zwh7d.webp",
        "link": "https://s.shopee.com.br/60M3D2NWzw",
        "highlight": false
    },
    {
        "id": 161,
        "name": "Conjunto Academia Feminino Alta Compressão Fitness Top e Short com Bolso",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ma4e4id9yzk1c2.webp",
        "link": "https://s.shopee.com.br/9fFLZmiq5j",
        "highlight": false
    },
    {
        "id": 162,
        "name": "Kit 17 Potes Herméticos Com Tampa Quadrados Empilháveis Acrílico",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9rdlxmr54559c.webp",
        "link": "https://s.shopee.com.br/5q2d0kSA4Y",
        "highlight": false
    },
    {
        "id": 163,
        "name": "QUEIMA DE ESTOQUE! Penteadeira Suspensa Com Espelho 70CM Console Camarim E&A - Cores",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbqrx9c6ujl302",
        "link": "https://s.shopee.com.br/20puRiKQ9i",
        "highlight": false
    },
    {
        "id": 164,
        "name": "Inox Prata Torneira Prata/Preto Com Chuveiro Com Rotação De 360° Cozinha Luxo Parede Promoção",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdluaa8bp39542.webp",
        "link": "https://s.shopee.com.br/6VIJnzPDgH",
        "highlight": false
    },
    {
        "id": 165,
        "name": "Cortinas Magnéticas De Proteção Solar Para Carros",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7rd5i-luqbeh3romw853.webp",
        "link": "https://s.shopee.com.br/2B9Ke2WVrG",
        "highlight": false
    },
    {
        "id": 166,
        "name": "Tapete Passadeira Vários Tamanhos Corredor Quarto Sala Beira de Cama Felpudo Peludo",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-macr7gj8pdvza4.webp",
        "link": "https://s.shopee.com.br/8pgEaJ2XIv",
        "highlight": false
    },
    {
        "id": 167,
        "name": "Mini Ar Condicionado Climatizador Umidificador Ventilador Portátil USB Led Quarto Sala Escritório Mesa Reservatório 600m",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/8zzemcWUf5",
        "highlight": false
    },
    {
        "id": 168,
        "name": "Kit Coala Laundry 1 Lava Roupas 5L + 2 Amaciantes de 1L cada - Chá Branco",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/1VtdqqhBDA",
        "highlight": false
    },
    {
        "id": 169,
        "name": "QUEIMA DE ESTOQUE! Armário Espelheira com Porta Cle - VÁRIAS CORES",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m4eljltmyhj51f.webp",
        "link": "https://s.shopee.com.br/7KrQnaGEp4",
        "highlight": false
    },
    {
        "id": 170,
        "name": "Jogo De Panelas Indução Kit 10 Peças Revestimento Cerâmico Style Cook Marmol - Mimo Style Premium",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m76wd3k5ex586a.webp",
        "link": "https://s.shopee.com.br/10xNFx4kMu",
        "highlight": false
    },
    {
        "id": 171,
        "name": "Varal De Chão De Roupas 3 Andares Dobrável Grande 4 Rodas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjsta6uqyigy2c.webp",
        "link": "https://s.shopee.com.br/BOGGR7W0I",
        "highlight": false
    },
    {
        "id": 172,
        "name": "Kit de Bolsa Térmica c/ 2 Compartimentos, Copo e Marmita, Porta Talher e Porta Escova",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mjse7rcauccic2.webp",
        "link": "https://s.shopee.com.br/4qA5p1c4sf",
        "highlight": false
    },
    {
        "id": 173,
        "name": "Kit 3 Bermudas Masculinas Básicas DryFit Malha Leve e Confortável Pronta Entrega Origins",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztf-mkponhmg8hs19b.webp",
        "link": "https://s.shopee.com.br/9zsByWn4LY",
        "highlight": false
    },
    {
        "id": 174,
        "name": "Kit Creme + Body Splash Feminino Aroma de Purê Hidratação e Perfume Inspirado em Fragrância Importada Primeira Linha",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mid64iyhaf4657.webp",
        "link": "https://s.shopee.com.br/3LLI2HuRhR",
        "highlight": false
    },
    {
        "id": 175,
        "name": "Organizador de maquiagem Acrílico Giratório 360º Suporte Para Cosméticos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m415wji061xdd5.webp",
        "link": "https://s.shopee.com.br/1BGnSJT5o2",
        "highlight": false
    },
    {
        "id": 176,
        "name": "Caixote de Madeira para Brinquedos, Caixa Organizadora de Madeira, Baú com rodas para Brinquedos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m5u2g1rfed1hd0.webp",
        "link": "https://s.shopee.com.br/6fbk0QYYKT",
        "highlight": false
    },
    {
        "id": 177,
        "name": "Kit 6 Peças de Roupas Infantil Menina Verão",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mge3pll6ed4w91.webp",
        "link": "https://s.shopee.com.br/AABcAs7cpf",
        "highlight": false
    },
    {
        "id": 179,
        "name": "KIT COMPLETO Diamond com borda dourada jarra 1L, 6 Taças 340ML, 6 Copos 370ML",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfjo83xsgyroa8.webp",
        "link": "https://s.shopee.com.br/6fbk0u9IvK",
        "highlight": false
    },
    {
        "id": 180,
        "name": "Kit Banheiro Em Bambu Com Lixeira Tampa Detalhes Luxo",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mk811k8al7nl51.webp",
        "link": "https://s.shopee.com.br/14q4eYgQd",
        "highlight": false
    },
    {
        "id": 181,
        "name": "Kit shampoo novo 1L Condicionador novo 1L mascara 500g óleo karseell novo.",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/1BGnSnUF3s",
        "highlight": false
    },
    {
        "id": 182,
        "name": "Kit 5 Escovas de Cabelo + Touca de Cetim – Raquete Fashion, Mágica, Polvo, Massageadora de Silicone",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9g746l2tekida.webp",
        "link": "https://s.shopee.com.br/10xNGUUsOr",
        "highlight": false
    },
    {
        "id": 183,
        "name": "Produto Shopee 183",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "assets/images/placeholder.png",
        "link": "https://s.shopee.com.br/qdx4BVVjq",
        "highlight": false
    },
    {
        "id": 184,
        "name": "36 Etiquetas para Potes de Condimentos Temperos Mantimentos 3,8x3,8cm",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7cz6del7s8i9c.webp",
        "link": "https://s.shopee.com.br/gKWrsW94p",
        "highlight": false
    },
    {
        "id": 185,
        "name": "Fatiador Profissional Multifuncional De Aço Inoxidável 16 Em 1 Para Vegetais/Frutas/Legumes",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/cn-11134207-7ras8-mbhvo90jyekt52.webp",
        "link": "https://s.shopee.com.br/4VXFQvHYIa",
        "highlight": false
    },
    {
        "id": 186,
        "name": "Bicicleta Ergométrica Bluetooth 2.0 Jogos AR para Spinning Mecanica SKYBOARD Roda de Inércia CD1210",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-madtyeom91n3f7.webp",
        "link": "https://s.shopee.com.br/4LDpEcIBdZ",
        "highlight": false
    },
    {
        "id": 187,
        "name": "Espelho Grande de Chão Oval com Moldura em Aluminio Corpo Inteiro Casamento Quarto Casa Decorativo Vestir",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7rdxp-mbqsre5bd1x174.webpg",
        "link": "https://s.shopee.com.br/4AuP2JIoyY",
        "highlight": false
    },
    {
        "id": 188,
        "name": "Eudora Siàge – Shampoo Condicionador Máscara Escolha o seu",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mk4b1wg3kjr537.webp",
        "link": "https://s.shopee.com.br/40ayq0JSJX",
        "highlight": false
    },
    {
        "id": 189,
        "name": "Conjunto Potes de Vidro com Tampa Bambu Cristal Porta Mantimentos Cozinha 3 Peças",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-malfycxrosr322.webp",
        "link": "https://s.shopee.com.br/5AmwE9F0wm",
        "highlight": false
    },
    {
        "id": 190,
        "name": "Parafusadeira Furadeira Sem Fio Com Completo Acessórios Caixa de Papelão Bivolt.",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/cn-11134207-7ras8-mdk3jhl2g4sp24.webp",
        "link": "https://s.shopee.com.br/50TW1qFeHl",
        "highlight": false
    },
    {
        "id": 191,
        "name": "Mop Spray Refil de Microfibra Com Reservatório",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m7z8j51wqyohad.webp",
        "link": "https://s.shopee.com.br/4qA5pXGHck",
        "highlight": false
    },
    {
        "id": 192,
        "name": "Kit 2 Balanças: Cozinha + Corporal | OliverHome",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mepwxwmmw2rlca.webp",
        "link": "https://s.shopee.com.br/4fqfdEGuxj",
        "highlight": false
    },
    {
        "id": 193,
        "name": "Kit 6 Toalha de Banho Grande Macia Premium 100% Algodão",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mevz64wssb9f38@resize_w900_nl.webp",
        "link": "https://s.shopee.com.br/3B1rqTMd0S",
        "highlight": false
    },
    {
        "id": 194,
        "name": "Jogo Americano Matelasse Cor Marrom Pvc",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/30iReANGLR",
        "highlight": false
    },
    {
        "id": 195,
        "name": "Kit C/12 Peças Utensílios De Cozinha Colheres Espatula Silicone Cabo Madeira Decoração Livre BPA",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcu9hg9lje2pb4.webp",
        "link": "https://s.shopee.com.br/2qP1RrNtgQ",
        "highlight": false
    },
    {
        "id": 196,
        "name": "Kit Banheiro Completo Lixeira C/ Tampa Detalhes Em Bambu Luxo",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mk811k8aieipfa.webp",
        "link": "https://s.shopee.com.br/2g5bFYOX1P",
        "highlight": false
    },
    {
        "id": 197,
        "name": "KIT 3 Regatas Casual Basica Suplex Duplo Blusa Feminina Blogueira Tendencia",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m5ycn6lcnqnmd1.webp",
        "link": "https://s.shopee.com.br/3qHYdhK5ee",
        "highlight": false
    },
    {
    },
    {
        "id": 198,
        "name": "KIT 12 Peças de Utensílios Para Cozinha em Silicone e Bambu",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/3VeiF5LMKc",
        "highlight": false
    },
    {
        "id": 199,
        "name": "Protetor Para Colchão 100% Impermeavel com Elastico em Toda Volta",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ltawffpuwxpwd8.webp",
        "link": "https://s.shopee.com.br/3LLI2mLzfb",
        "highlight": false
    },
    {
        "id": 200,
        "name": "Chaleira Elétrica Térmica Bule Com Tampa Inox 1,8L",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m171eda30l83f9.webp",
        "link": "https://s.shopee.com.br/7AY0bp7OtM",
        "highlight": false
    },
    {
        "id": 201,
        "name": "Bicicleta Aro 29 Aço Carbono KGT Freios A Disco 21 Marchas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mehrpj8fs4chae.webp",
        "link": "https://s.shopee.com.br/70EaPW82EL",
        "highlight": false
    },
    {
        "id": 202,
        "name": "Produto Shopee 203",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "assets/images/placeholder.png",
        "link": "https://s.shopee.com.br/6pvADD8fZK",
        "highlight": false
    },
    {
        "id": 203,
        "name": "Kit Porta Frios com Tampa Duplo Hermético 770ml Para Queijo Presunto Pote Mantimentos Acrilico",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me8olrxqhog23c.webp",
        "link": "https://s.shopee.com.br/6fbk0u9IuJ",
        "highlight": false
    },
    {
        "id": 204,
        "name": "Arranjo c/ 3 Trepadeira Folha de HERA + Vaso Trançado Marrom",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-md3o52t872giaa.webp",
        "link": "https://s.shopee.com.br/7pnhP34rXY",
        "highlight": false
    },
    {
        "id": 205,
        "name": "Conjunto Fitness Feminina Para Treino Super Confortável Com Bojo Short Roupa Para Academia",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m8uuibkdw35ubf.webp",
        "link": "https://s.shopee.com.br/7fUHCk5UsX",
        "highlight": false
    },
    {
        "id": 206,
        "name": "Kit 3/6/12 Taças Copo Diamond Vidro Transparente Para Bebidas 340ml",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztm-mkjm0gx1h79ed7.webp",
        "link": "https://s.shopee.com.br/7VAr0R68DW",
        "highlight": false
    },
    {
        "id": 207,
        "name": "Stick de blush multi-funções-Cor natural de longa duração para maquiagem feminina",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7ratk-ma9o18kpxdf86b.webp",
        "link": "https://s.shopee.com.br/7KrQo86lYV",
        "highlight": false
    },
    {
        "id": 208,
        "name": "Camiseta Treino Feminina Docinho Oversized Roupas de Academia Look de Treino Super Poderosas Meme",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/5q2d1NCTbE",
        "highlight": false
    },
    {
        "id": 209,
        "name": "Kit 11 potes de vidro com tampa de bambu herméticos redondos - Tüd",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7rdya-m1cvhjnkfted65.webp",
        "link": "https://s.shopee.com.br/5fjCp4D6wD",
        "highlight": false
    },
    {
        "id": 210,
        "name": "Kit 5 Calcinha Sem Costura Não Marca Calcinha Corte a Laser Tanga",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7reqk-mdurrxc2y2jv4d.webp",
        "link": "https://s.shopee.com.br/5VPmclDkHC",
        "highlight": false
    },
    {
        "id": 211,
        "name": "Manta Sofá Luxo Gigante 2,10x1,20 - Protetora e Decorativa Cores Variadas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mfjw1uipc4qtb3.webp",
        "link": "https://s.shopee.com.br/5L6MQSENcB",
        "highlight": false
    },
    {
        "id": 212,
        "name": "Kit 20 Esmalte Impala Cremoso Hipoalergenico Cor da Sua Moda esmalte Kit Manicure Completo",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ma4490eu9qpt2e.webp",
        "link": "https://s.shopee.com.br/6VIJob9wFQ",
        "highlight": false
    },
    {
        "id": 213,
        "name": "Kit Cronograma Capilar Completo Karseell – 3 Máscaras (Hidratação, Nutrição e Reconstrução)",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/6KytcIAZaP",
        "highlight": false
    },
    {
        "id": 214,
        "name": "Kit Ferramentas Manuais Fasterr 189 Peças com Maleta Dobrável Completa - Fasterr",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m54qt7w35jua7f.webp",
        "link": "https://s.shopee.com.br/6AfTPzBCvO",
        "highlight": false
    },
    {
        "id": 215,
        "name": "Kit potes de mantimentos cozinha com 9 peças de plástico decorado",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mcpp13simxbm6f.webp",
        "link": "https://s.shopee.com.br/60M3DgBqGN",
        "highlight": false
    },
    {
        "id": 216,
        "name": "Kits Pares de Meias Soquete Cano Curto Masculina Feminina Unissex varejo",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mk1bp5i3xreoa6.webp",
        "link": "https://s.shopee.com.br/9pYlmixFU8",
        "highlight": false
    },
    {
        "id": 217,
        "name": "Projetor 4K HD, adequado para celular, TV Box, Xbox, PS, PC, suporte WiFi, HY300 Pro Magcubic, envio imediato",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-7ratt-mb4orzzejhiuac.webp",
        "link": "https://s.shopee.com.br/9fFLaPxsp7",
        "highlight": false
    },
    {
        "id": 218,
        "name": "Carregador Portátil Mini Power Bank 10000mAh Com 02 Saídas Tipo-C / Lightning",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mf41ipxjrwg70d.webp",
        "link": "https://s.shopee.com.br/9UvvO6yWA6",
        "highlight": false
    },
    {
        "id": 219,
        "name": "Jogo de Panelas Legacy Antiaderente Revestimento Cerâmico 5 Peças Tampa de Vidro",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mf2p13dq5h53e2.webp",
        "link": "https://s.shopee.com.br/9KcVBnz9V5",
        "highlight": false
    },
    {
        "id": 220,
        "name": "Espuma Spray Zip Clean 300ml Limpa a Seco Sofá, Estofado, Banco de Carro Limpeza Profunda",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mhnxjh409bsz8a.webp",
        "link": "https://s.shopee.com.br/AUoSZwui8K",
        "highlight": false
    },
    {
        "id": 221,
        "name": "Chinelo Ortopedico Modare Feminino Esporão Massageador Macio",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mki76xc6s2yo55.webp",
        "link": "https://s.shopee.com.br/AKV2NdvLTJ",
        "highlight": false
    },
    {
        "id": 222,
        "name": "Kit 3 Calças Legging Feminina Academia Fitness Cintura Alta Levanta Bumbum Zero Transparência",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mbr89tf5jyopa6.webp",
        "link": "https://s.shopee.com.br/AABcBKvyoI",
        "highlight": false
    },
    {
        "id": 223,
        "name": "Kit Casa Limpa Coala/Zulu Perfumes - Chá Branco",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/9zsBz1wc9H",
        "highlight": false
    },
    {
        "id": 224,
        "name": "Escolha seu Kit Organizadores de Geladeira e Armário 3,8L – Cestos Acrílico Transparente para Cozinha, Frutas, Verduras",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-me5wiafov5z4c5.webp",
        "link": "https://s.shopee.com.br/8V3OCH2KC0",
        "highlight": false
    },
    {
        "id": 225,
        "name": "Kit Menina Sandália Infantil com Bolsinha Linda e Delicada",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m9rqqbhz6xq1e0.webp",
        "link": "https://s.shopee.com.br/8Kjxzy2xWz",
        "highlight": false
    },
    {
        "id": 226,
        "name": "Limpador Pincel Esponja Maquiagem Elétrico USB Automático Lava Seca Armazena",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/8AQXnf3ary",
        "highlight": false
    },
    {
        "id": 227,
        "name": "Garrafa Alumínio Infantil Buba 450ml Canudo Retrátil | Escolar Verão | 4 Temas Divertidos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/8077bM4ECx",
        "highlight": false
    },
    {
        "id": 228,
        "name": "Frigideira Multifuncional Antiaderente 4 Em 1 Para Ovos , Hambúrguer , Omelete , Com Cabo De Madeira",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/cn-11134207-7ras8-m3celow5ym7j3e.webp",
        "link": "https://s.shopee.com.br/9AJ4zUzmqC",
        "highlight": false
    },
    {
        "id": 229,
        "name": "Jogos de Tapetes para Banheiro Peças | Algodão Pelúcia Macio Antiderrapante Conjunto",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/8zzenC0QBB",
        "highlight": false
    },
    {
        "id": 230,
        "name": "Kit 10 Limpador de máquina de lavar, comprimido efervescente sólido para remover manchas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lv98cwwitsix1e.webp",
        "link": "https://s.shopee.com.br/8pgEat13WA",
        "highlight": false
    },
    {
        "id": 231,
        "name": "Panela de Pressão Elétrica 6L 1000W PPE102 - Kian",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/sg-11134201-824i6-mf9p0jie6byk23.webp",
        "link": "https://s.shopee.com.br/3B1rqTMd1V",
        "highlight": false
    },
    {
        "id": 232,
        "name": "Rede Cadeira Balanço Descanso Teto Suspensa Trançada Reforçada - Varias Cores",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/2g5bFYOX2Q",
        "highlight": false
    },
    {
        "id": 233,
        "name": "Kit Colcha Cobre Leito Casal Queen King 3 Peças Estampada Florida Matelado Boutis Percal Cama Box",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mkb221yy1t6rc2.webp",
        "link": "https://s.shopee.com.br/2qP1RrNthT",
        "highlight": false
    },
    {
        "id": 234,
        "name": "Saia de carnaval de fitas metalizadas fitilho coloridas várias cores",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/3fy8ROKj0e",
        "highlight": false
    },
    {
        "id": 235,
        "name": "Kit Cetim Antifrizz 2 Fronhas Touca de Cetim Regulável Xuxinha Scrunchie Cabelo para Dormir",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/3qHYdhK5fh",
        "highlight": false
    },
    {
        "id": 236,
        "name": "Kit com 02/05/10 Calcinha Importada Shortinho Infantil Estampado para Menina Tam 02 a 10 Anos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-meow4736yy9te3.webp",
        "link": "https://s.shopee.com.br/3LLI2mLzgc",
        "highlight": false
    },
    {
        "id": 237,
        "name": "Mangueira de Jardim Anti-Torção e Anti-Dobras de 5 a 50 Metros",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m4zac7gestxh75.webp",
        "link": "https://s.shopee.com.br/3VeiF5LMLf",
        "highlight": false
    },
    {
        "id": 238,
        "name": "Ventilador de Teto com Luz Silencioso Controle Remoto Economica E27 Instalação Fácil LED Bivolt",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/70EaPW82FM",
        "highlight": false
    },
    {
        "id": 239,
        "name": "Esfoliante Corpo e Rosto Cheiro de Fruta Labotrat 300g ou 150g - maracujá - melancia - morango - pitaya - pêssego",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mb2lqxmr1xx59b.webp",
        "link": "https://s.shopee.com.br/7AY0bp7OuP",
        "highlight": false
    },
    {
        "id": 240,
        "name": "Kit 1,2 e 4 Organizador de Geladeira 3,8 Litros Cesto ou 2,8 Com Tampa Multiuso Alimento Verdura e Vegetal",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mawuakidj1tl1e.webp",
        "link": "https://s.shopee.com.br/3qHYdJKutZ",
        "highlight": false
    },
    {
        "id": 241,
        "name": "Garrafa De Água Infantil Interativa Educacional Com Cores E Tabuada Números E Contas interativa De Contas Giratórias",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/cn-11134207-7ras8-md69su8u8m7d08.webp",
        "link": "https://s.shopee.com.br/3LLI2OMouU",
        "highlight": false
    },
    {
        "id": 242,
        "name": "Capa Para Colchão Impermeavel Matelado Com Elastico",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-ltwjwwwq5uudff.webp",
        "link": "https://s.shopee.com.br/3VeiEhMBZX",
        "highlight": false
    },
    {
        "id": 243,
        "name": "Bicicleta Aro 29 KGT Aço Carbono Freios a Disco Suspensão 21 Marchas",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mehrx80heupvf0.webp",
        "link": "https://s.shopee.com.br/4LDpEEJ0si",
        "highlight": false
    },
    {
        "id": 244,
        "name": "Balança Bioimpedância Medidora Corporal Bluetooth Até 180 Kg + Balança De Cozinha Precisão Digital 1g Até 10 Kg",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgwp8l5n2uww9d.webp",
        "link": "https://s.shopee.com.br/4VXFQXINXl",
        "highlight": false
    },
    {
        "id": 245,
        "name": "Repelente Eletrônico Ultrassônico Mosca Pernilongos Baratas Morcegos repele e Espanta Ratos bivolt",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134258-7r98o-mbpr92sw6g6132",
        "link": "https://s.shopee.com.br/40aypcKHYg",
        "highlight": false
    },
    {
        "id": 246,
        "name": "Fatiador de cozinha multifuncional profissional em aço inoxidável 16 em 1 fatiador de vegetais/frutas/legumes",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/cn-11134207-7ras8-maozriowdjfw01.webp",
        "link": "https://s.shopee.com.br/4AuP1vJeDj",
        "highlight": false
    },
    {
        "id": 247,
        "name": "Kit Capa Almofada Fita Losango Azul Jeans Manta Grande Decorativa Sofa Cama Rustica Carnaval",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134211-81ztc-mjymjbyk0b29cc.webp",
        "link": "https://s.shopee.com.br/50TW1SGTWu",
        "highlight": false
    },
    {
        "id": 248,
        "name": "Chinelo Feminino Plataforma Trançado Ortopédico Confortável",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-m8h3ee2kf5ldf0.webp",
        "link": "https://s.shopee.com.br/5AmwDlFqBx",
        "highlight": false
    },
    {
        "id": 249,
        "name": "Kit com 5 Potes de Vidro tigela com Tampa –135 ml, 200 ml, 400 ml, 550 ml, 1000 ml|alimentos",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mk2kqwup27lvc9.webp",
        "link": "https://s.shopee.com.br/4fqfcqHkCs",
        "highlight": false
    },
    {
        "id": 250,
        "name": "Varal de Roupa de Parede Retrátil de alumínio para Sacada Até 80kg",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mbs4ympirtlzb0@resize_w900_nl.webp",
        "link": "https://s.shopee.com.br/4qA5p9H6rv",
        "highlight": false
    },
    {
        "id": 251,
        "name": "Robô Varredora/Aspirador De Pó 1200PA Automática 3 Em 1 Limpeza Doméstica Robótico Inteligente E Silencioso",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-lo8epw1nrmbw14.webp",
        "link": "https://s.shopee.com.br/LhgSsYF04",
        "highlight": false
    },
    {
        "id": 252,
        "name": "Mesa para Notebook Mesinha para Computador Portátil Cama para estudos com Gaveta Dobravel",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81z1k-mgglvb6ir9q8bb.webp",
        "link": "https://s.shopee.com.br/W16fBXbf7",
        "highlight": false
    },
    {
        "id": 253,
        "name": "Caixa Térmica Cooler Premium 32L 3 em 1 Multifuncional com Mesa e Rodas Praia Camping Churrasco",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-81ztc-mj8ilwi6wydd4b.webp",
        "link": "https://s.shopee.com.br/14q4GZVg2",
        "highlight": false
    },
    {
        "id": 254,
        "name": "Varal De Chão Roupa Calcinha Grade 3 Andares Dobrável Portátil",
        "category": "shopee",
        "price": 0.00,
        "oldPrice": null,
        "description": "Oferta Shopee. Clique para conferir.",
        "image": "https://down-br.img.susercontent.com/file/br-11134207-7r98o-mdarhuorrgg19a.webp",
        "link": "https://s.shopee.com.br/BOGGZYsL5",
        "highlight": false
    }
];
